cargo-features = ["edition2021"]
[package]
name = "silabize-es"
version = "0.1.0"
authors = ["Weiwei Wang <gastlygem@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"