name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: component
      uses: actions-rs/components-nightly@v1
      with:
        component: cargo
      # run: cargo build --verbose && cargo test --verbose
